# Generated by Django 6.0.3 on 2026-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_familiar_nome_interno_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='encaminhamento',
            field=models.CharField(blank=True, choices=[('politica_publica', 'Política Pública'), ('mercado_trabalho', 'Mercado de Trabalho'), ('cursos_capacitacoes', 'Cursos e Capacitações')], max_length=30),
        ),
        migrations.AddField(
            model_name='familiar',
            name='encaminhamento_detalhe',
            field=models.TextField(blank=True),
        ),
    ]
