# Generated by Django 5.2.13 on 2026-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_familiar_nome_interno_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='comorbidades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='deficiencias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='experiencia_trabalho',
            field=models.CharField(blank=True, choices=[('formal', 'Experiência formal'), ('informal', 'Experiência informal'), ('formal_informal', 'Experiência formal e informal'), ('sem_experiencia', 'Sem experiência de trabalho'), ('nao_informado', 'Não informado')], max_length=30),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='possui_comorbidade',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_informado', 'Não informado')], max_length=15),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='substancias_psicoativas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_ocupacao',
            field=models.CharField(blank=True, choices=[('estudante', 'Estudante'), ('formal', 'Ocupação formal'), ('informal', 'Ocupação informal'), ('pensionista_aposentado', 'Pensionista e/ou aposentado'), ('sem_ocupacao', 'Sem ocupação'), ('nao_informado', 'Não informado')], max_length=30),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='uso_substancias_psicoativas',
            field=models.CharField(blank=True, choices=[('nunca', 'Nunca fez uso'), ('uso_anterior', 'Fez uso anteriormente'), ('uso_atual', 'Faz uso atualmente'), ('uso_anterior_atual', 'Fez uso anteriormente e faz uso atualmente'), ('nao_informado', 'Não informado')], max_length=30),
        ),
        migrations.AddField(
            model_name='familiar',
            name='comorbidades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='deficiencias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='experiencia_trabalho',
            field=models.CharField(blank=True, choices=[('formal', 'Experiência formal'), ('informal', 'Experiência informal'), ('formal_informal', 'Experiência formal e informal'), ('sem_experiencia', 'Sem experiência de trabalho'), ('nao_informado', 'Não informado')], max_length=30),
        ),
        migrations.AddField(
            model_name='familiar',
            name='grau_instrucao',
            field=models.CharField(blank=True, choices=[('nao_informado', 'Não informado'), ('nao_alfabetizado', 'Não alfabetizado'), ('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('fundamental_completo', 'Ensino Fundamental Completo'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('superior_incompleto', 'Ensino Superior Incompleto'), ('superior_completo', 'Ensino Superior Completo'), ('pos_graduacao_incompleta', 'Pós-Graduação Incompleta'), ('pos_graduacao_completa', 'Pós-Graduação Completa')], max_length=30),
        ),
        migrations.AddField(
            model_name='familiar',
            name='identidade_genero',
            field=models.CharField(blank=True, choices=[('mulher_cis', 'Mulher cis'), ('homem_cis', 'Homem cis'), ('mulher_trans', 'Mulher trans'), ('homem_trans', 'Homem trans'), ('travesti', 'Travesti'), ('nao_binario', 'Não binário'), ('outro', 'Outro'), ('nao_informado', 'Prefiro não informar')], max_length=20),
        ),
        migrations.AddField(
            model_name='familiar',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='familiar',
            name='possui_comorbidade',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_informado', 'Não informado')], max_length=15),
        ),
        migrations.AddField(
            model_name='familiar',
            name='serie_concluida',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='familiar',
            name='substancias_psicoativas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='tipo_ocupacao',
            field=models.CharField(blank=True, choices=[('estudante', 'Estudante'), ('formal', 'Ocupação formal'), ('informal', 'Ocupação informal'), ('pensionista_aposentado', 'Pensionista e/ou aposentado'), ('sem_ocupacao', 'Sem ocupação'), ('nao_informado', 'Não informado')], max_length=30),
        ),
        migrations.AddField(
            model_name='familiar',
            name='uso_substancias_psicoativas',
            field=models.CharField(blank=True, choices=[('nunca', 'Nunca fez uso'), ('uso_anterior', 'Fez uso anteriormente'), ('uso_atual', 'Faz uso atualmente'), ('uso_anterior_atual', 'Fez uso anteriormente e faz uso atualmente'), ('nao_informado', 'Não informado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='grau_instrucao',
            field=models.CharField(blank=True, choices=[('nao_informado', 'Não informado'), ('nao_alfabetizado', 'Não alfabetizado'), ('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('fundamental_completo', 'Ensino Fundamental Completo'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('superior_incompleto', 'Ensino Superior Incompleto'), ('superior_completo', 'Ensino Superior Completo'), ('pos_graduacao_incompleta', 'Pós-Graduação Incompleta'), ('pos_graduacao_completa', 'Pós-Graduação Completa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='identidade_genero',
            field=models.CharField(blank=True, choices=[('mulher_cis', 'Mulher cis'), ('homem_cis', 'Homem cis'), ('mulher_trans', 'Mulher trans'), ('homem_trans', 'Homem trans'), ('travesti', 'Travesti'), ('nao_binario', 'Não binário'), ('outro', 'Outro'), ('nao_informado', 'Prefiro não informar')], max_length=20),
        ),
    ]
