# Generated by Django 6.0.3 on 2026-04-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_familiar_encaminhamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(blank=True, max_length=120)),
                ('vara_comarca', models.CharField(blank=True, max_length=255)),
                ('tipo_processo', models.CharField(blank=True, max_length=255)),
                ('situacao_juridica_atual', models.TextField(blank=True)),
                ('situacao_juridica_outro', models.CharField(blank=True, max_length=255)),
                ('encaminhamentos_setor', models.TextField(blank=True)),
                ('encaminhamentos_setor_outro', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_juridico_registros', to='core.cadastro')),
                ('familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_juridico_registros', to='core.familiar')),
            ],
        ),
    ]
