# Generated by Django 6.0.3 on 2026-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_setorjuridico'),
    ]

    operations = [
        migrations.AddField(
            model_name='setorjuridico',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='setor_juridico_docs/'),
        ),
    ]
